### ISSUE TITLE
Can't get "from" value in function match_event_handler 

### ISSUE THREAD

**Issue by jassls** [intel/hyperscan#117]
Hi guys, 
    There's a question made me confused, if I don't use HS_FLAG_SOM_LEFTMOST, then I always can't get the "from" value in the function match_event_handler. (but "to" value is ok ). "from" always 0 !
    Thanks a lot !

**Comment by xiangwang1** [comment]
Hi Jassls,

Hyperscan doesn't support start of match by default. In many use cases, the "from" value is not a mandatory requirement. Furthermore, delivering "from" value impacts the overall performance as it involves more complex analyses to find the value. So we don't recommend enabling start of match for performance considerations and the users need to explicitly turn it on with the HS_FLAG_SOM_LEFTMOST flag.

That's why you always get a "from" of value 0.

Thanks,
Xiang

**Comment by jassls** [comment]
Hi xiangwang1:
    非常感谢。另外如果设置上HS_FLAG_SOM_LEFTMOST以后，我发现对于一个贪婪的正则表达式，会按照从左最短匹配开始，向右依次返回命中的正则部分，多次调用match_event_handler.  比如正则是a+, 实际的文本是aaaa, 则会进入4次match_event_handler, 每次进入match_event_handler后to的值分别是1,2,3,4.

那么请问如果我既希望使用match_event_handler的from参数，又希望正则匹配的时候按照最贪婪的方式只匹配最长的部分，是不是就没办法实现了？

**Comment by xiangwang1** [comment]
The fundamental theory behind Hyperscan is state machine traversal without expensive backtracking behaviors. So Hyperscan doesn't tell greedy or non-greedy syntax, instead it reports all the matches. 

You can try Chimera if need to be fully compatible with PCRE syntax. But it will get worse performance than Hyperscan.

Thanks,
Xiang

**Comment by xiangwang1** [comment]
Close as this is a normal behavior of Hyperscan based on design considerations.
