### ISSUE TITLE
64 bits data length in hs_scan functions

### ISSUE THREAD

**Issue by delins** [intel/hyperscan#118]
`hs_scan`, `hs_scan_vector` and `hs_scan_stream` use an `unsigned int` parameter for providing the length of the buffer to scan. This effectively limits the length to 4GB-1. 

I suppose this choice came from hyperscan being targeted at fields like DPI, where it is a sensible size. However, I was hoping to use hyperscan for pattern matching on large buffers, such as memory-mapped hard drives which may be multiple TBs.

Is it possible to increase the length parameter to a 64 bit unsigned int? Would you implement this in the near future? If not, could you tell me if we can actually fully use the 4GB length that the unsigned int suggests, or is there an internal, lower limit?

This limitation could of course be circumvented by using vector mode with multiple 2GB blocks for instance, but I'm hoping for a nicer solution :)

**Comment by xiangwang1** [comment]
Yes, Hyperscan is majorly targeting at DPI solutions, and we don't have a specific plan for 64-bit length so far which requires a large amount of type conversions internally.
No issues using 4GB as we don't impose any lower limits in the code. As you said, vector mode is a workaround for your issue that is likely to have a close performance to normal block mode in most cases.

**Comment by delins** [comment]
Thanks for the reply.

So can I conclude that using Hyperscan this way is supported in the API? Or does it just happen to work given the current implementation? I'm wary of using implementation-specific functionality as this may change in the future.

Also, when scanning 1 TB of (virtual) memory, will match offsets be reported correctly, especially when HS_FLAG_SOM_LEFTMOST is given and scanning is performed in streaming mode? Any or both of these properties often impose some limits according to the API.

**Comment by xiangwang1** [comment]
Yes, I don't expect further API changes that may impact your use case.

Streaming mode is an alternative of vector mode - they are basically sharing the same implementation internally. So you can choose streaming mode to scan multiple blocks of data as well in your case. The limits from streaming mode with SOM opposed to block mode come from slightly weaker pattern support. But once patterns are compiled successfully, it is guaranteed to deliver correct matching offsets. 
  
I think it looks fine to me since the `from` and `to` offsets in user's callback function are defined as `unsigned long long`. Feel free to reach us if you encounter any issues.

**Comment by delins** [comment]
Ok I'll perform some tests in the near future and let you know how it goes

**Comment by delins** [comment]
I wasn't expecting "near future" to be 2.5 years, but here goes: I have been using hyperscan on large files for a while now, using streaming mode. I basically cut the input up in <4GB chunks and loop over them. The added benefit of the smaller chunks as opposed to scanning the large file all in one go is that you may pause or stop the search before it's finished. So I would probably have chosen this approach regardless of any `int` limits.
