### ISSUE TITLE
Numerical result out of range Error, before running main

### ISSUE THREAD

**Issue by rxdelta** [intel/hyperscan#155]
check this code (`hs-error-34.c`):
```
#include <stdint.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <hs/hs.h>

typedef struct {
    hs_database_t* database;
    hs_scratch_t*  scratch;
} regex;

void foo(regex* r, const char* data, unsigned int len) {
        hs_scan(r->database, data, len, 0, r->scratch, NULL, NULL);
}

int main() {
        if (errno != 0) printf("ERROR(%d): %s\n", errno, strerror(errno));
        return errno;
}

```
compile & run it:
`gcc hs-error34.c -lhs -Wall && ./a.out`
see the error:
`ERROR(34): Numerical result out of range`
if you comment `foo` function, the error will be gone
Any idea?

**Comment by Nor7th** [comment]
Hi,
Can you provide your basic configurations and lib setup steps for this test? (Including gcc version, build commands, lib version, etc, the more the better.)
We just tried to build the lib from v5.1.1 source file with no cmake parameters, and seems to be unable to see this error under gcc 5.5.0 and 7.2.0.
Thanks.

**Comment by rxdelta** [comment]
Hi Nor7th,
sure, I've tested on two machines with these specs, respectively:
machine-1)
OS: `Ubuntu 18.04.1 LTS`
GCC: `7.3.0-27ubuntu1~18.04`
libhyperscan4  +dev: `4.7.0-1`

machine-2)
OS: `Ubuntu 16.04.3 LTS`
GCC: `5.4.0-6ubuntu1~16.04.4`
libhyperscan5  +dev: `5.0.0-3`

I will try the latest version of libhyperscan5 and share the result with you

Best regards, rXδelta

**Comment by rxdelta** [comment]
I've tested with updated libhyperscan5 +dev, and unfortunately, the error is still exists
OS: `Ubuntu 18.04.1 LTS` , arch: `amd64`
GCC: `7.3.0-27ubuntu1~18.04`
libhyperscan5 +dev: `5.1.1-1`

I think I need to share more information with you, just tell me what else could help

Best regards, rXδelta

**Comment by Nor7th** [comment]
Hi rXδelta,

We think it's an internal bug from our code. A simple fix will be provided in our next release.

The culprit is in line 285 of fdr_compile.cpp:
https://github.com/intel/hyperscan/blob/7729ade0fa291cedb3cbbebb3bafcb9fb8ece81b/src/fdr/fdr_compile.cpp#L284-L286
The first element `pow{0, -3.0}` is what leads to the `ERROR(34): Numerical result out of range`. If the parameter `0` here is replaced with some other proper value like `0.5`, error will be gone.

However, we still don't have a good explanation for the root cause.

We found that whether this issue appears depends on the library usage. To make it clear, following lists all stuffs in a Hyperscan released lib (take `libhyperscan4 + dev`  for example):

> libhs.a
> libhs_runtime.a
> libhs_runtime.so -> libhs_runtime.so.4
> libhs_runtime.so.4 -> libhs.runtime.so.4.7.0
> libhs_runtime.so.4.7.0
> `libhs.so` -> libhs.so.4
> libhs.so.4 -> libhs.so.4.7.0
> libhs.so.4.7.0

Shared lib link `libhs.so` is used by default, in this case, we see this strange `errno` value. But if static lib `libhs.a` is used, this error never shows up, no matter whether the hs_scan() is commented or not. Thus, this error only appears when we use shared lib, and meanwhile leave the hs_scan() function there but never call it.

A general suspicion might be that the compiler only does some checking work at such a case before execute main(). But we have still not been very confident about the real mechanism yet.

**Comment by rxdelta** [comment]
Great Job Nor7th! it is so hard to find such errors!

power(0,-3) = 1/power(0,3) = inf.
That make sense, this part of code is static and called before The main routine, even if it used as shared object(.so) (see man page for dlopen() and _init() function in dynamic shared libraries)

P.S. pow(0,-3) is unused in your code, if you look at this function, len==0 is excluded
https://github.com/intel/hyperscan/blob/7729ade0fa291cedb3cbbebb3bafcb9fb8ece81b/src/fdr/fdr_compile.cpp#L253-L258
 feel free to replace `pow(0,-3.0)` with `0`

**Comment by rxdelta** [comment]
replaced with 0: https://github.com/intel/hyperscan/pull/161
