### ISSUE TITLE
hyperscan非法指令

### ISSUE THREAD

**Issue by yuhao0603** [intel/hyperscan#199]
hi,
我在使用hyperscan的过程中，发现hyperscan的bitfiled.h这个文件里的set_range中的 一行代码block_type block = all_ones << (from % block_size);
编译出了一条shlx移位指令，这条指令在某些cpu上是不支持的，请问这种问题有什么办法规避掉吗

**Comment by xiangwang1** [comment]
hi @yuhao0603,

`shlx` is from BMI2 instruction set which is introduced by Haswell architecture. 

I think if you compile hyperscan binary and running it on the same machine, the compiler will detect your CPU architecture and generate the appropriate binary. 
Otherwise, you need to specify the architecture of target machine for the compiler locally (e.g. `cmake -DCMAKE_C_FLAGS="-march=core2" 
  -DCMAKE_CXX_FLAGS="-march=core2" <hyperscan-source-path>`

**Comment by yuhao0603** [comment]
感谢回答，我查到haswell架构是intel从第四代采用的。那么可以理解为，四代及以后的cpu都支持bmi2指令集吗

**Comment by xiangwang1** [comment]
Yes, any later generation will have BMI2.

**Comment by yuhao0603** [comment]
好的，十分感谢
