### ISSUE TITLE
Hyperscan Prefilter Support

### ISSUE THREAD

**Issue by Its-Yasir** [intel/hyperscan#204]
Hey there,
I am running Hyperscan with Snort 2.9.9.0 and it gives certain warnings during Snort startup.
**Hyperscan could not prefilter PCRE: /^.*?(\x5c.){256}/s**
**Hyperscan could not prefilter PCRE: /(^a\x3Drtpmap\x3A[^\n]*\r\n){31}/Psmi**
**Hyperscan could not prefilter PCRE: /(^Accept:\s\w*[\n\r]*){33}$/Hmi**

What does this means? Does such pcre(s) doesn't work in Hyperscan?

**Comment by xiangwang1** [comment]
Hi @Its-Yasir 
These are warnings of unsuccessful prefiltering. In this case, Snort will run PCRE library instead of Hyperscan for these rules which won't impact the overall results. You can just ignore them. 

Hyperscan has a prefiltering feature which transforms an unsupported PCRE rule into a supported one, but the transformed rule will generate a super set of matches.
Since Hyperscan is usually much faster than PCRE library, we leverage this feature as a fast filter in Snort and only trigger PCRE library when there are matches found in the filter for unsupported rules.
