### ISSUE TITLE
SIMD

### ISSUE THREAD

**Issue by BiBi-Abc** [intel/hyperscan#276]
I was wondering, how does this SIMD work?

I have a AMD Ryzen 9 3900x, which supports everything to AVX2, but not AVX512.
When I compiled hyperscan on Windows, it said that it was NOT using AVX2 instructions for some reason.
I compiled with this:
```
cmake -G "Visual Studio 2019 16" sourceDir
```

Why is that?
Also, I was wondering, say I compile WITH Avx2 support on my CPU. If I move the program to another computer which only has SSSE3 support, will hyperscan still work?
Also, say I compile WITH Avx2 support on my CPU. Will a computer with AVX512 instructions use the 512 instructions?

**Comment by xiangwang1** [comment]
We currently have a limited SIMD support on Windows with only SSSE3 on due to some compatibility issues.
But Hyperscan delivers full SIMD support on Linux.

In general, the compile time analysis determines which instructions to use at run-time: 
- You can't run AVX2 version of database on a CPU with only SSSE3.
- You can't run AVX512 instructions if the database is only compiled with AVX2 support.

**Comment by saosir** [comment]
> We currently have a limited SIMD support on Windows with only SSSE3 on due to some compatibility issues. But Hyperscan delivers full SIMD support on Linux.
> 
> In general, the compile time analysis determines which instructions to use at run-time:
> 
> * You can't run AVX2 version of database on a CPU with only SSSE3.
> * You can't run AVX512 instructions if the database is only compiled with AVX2 support.

Will the compiled database be backward compatible? For example, files compiled by the AVX2 machine can be loaded on avx512
