### ISSUE TITLE
Pattern matching with hyperscan

### ISSUE THREAD

**Issue by ituronova** [intel/hyperscan#282]
I succesfully compiled hyperscan library but that it. Could you please help me how to do pattern matching with it?

I want to use it as for example grep:

grep -c "a{3}" inputText.txt 

such that it would return a number of matching lines.

**Comment by xiangwang1** [comment]
You can refer to our example at https://github.com/intel/hyperscan/blob/master/examples/simplegrep.c about how to do pattern matching with Hyperscan. 
In addition, similar to other regex matching libraries (PCRE, RE2, etc) and different from grep, Hyperscan reports matching offsets instead of matching lines.
