### ISSUE TITLE
MacOS build broken?

### ISSUE THREAD

**Issue by eliaslevy** [intel/hyperscan#69]
Attempting to build 4.6.0 on MacOS 10.12.6 using Xcode 9.0 result in failure at the link stage with about 100 errors C++ symbols that it can't find.

E.g.
```
  "std::logic_error::what() const", referenced from:
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag> > in ng_depth.o
```
```
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const", referenced from:
      ue2::ComponentCondReference::addAlternation() in ComponentCondReference.o
```

**Comment by mdb256** [comment]
Thanks for raising this issue.

This appears to only affect builds with shared libraries using CMake's Xcode generator.

What seems to be happening is that the link command for `libhs.dylib` is not linking to `libc++` - CMake is not marking it as a library that needs C++ linkage. Some quick testing shows that adding a dummy C++ file to the library appears to fix the problem, but the more correct method of setting the `LINKER_LANGUAGE` property doesn't seem to work. This needs more investigation.

The reason is it failing in v4.6.0 is because we slightly changed how the shared lib is built since v4.5.2.

A workaround for the time being is to use the CMake `Unix Makefiles` generator - that is, the default CMake generator - which would mean building with `make` instead of Xcode.

**Comment by mdb256** [comment]
I've added 3d235f4 to the develop branch which adds a dummy C++ file to the library, which makes CMake/Xcode build libhs_runtime.dylib with C++ linkage.

**Comment by captkurt10** [comment]
I'm new to XCode and ran into this issue with exact same software & hardware configuration. In a CMake built target my ObjC code would run fine however, in the same XCode project, a XCTest target would result in the 100+ linkage errors described above. The mobile guy on my team had me try adding the lib 'libc++.tbd' to my XCode > Build_Phases > Link_Binary_With_Libraries '. Worked!
